language: python

python:
  - 3.3
  - 3.4
  - 3.5
  - pypy3

install:
  - pip install PyYAML
  - pip install coveralls

script:
  - coverage run --branch --source configuration -m py.test

after_success:
  - coveralls
